@startsalt notificarGuiasActualizadas-wireframe
{
    <b>GUÍAS DEL PROGRAMA -- GII</b>
    ====
    {#
        <b>AsignaturaPrograma | <b>Profesorado | <b>Estado | .
        Programación I | Dr. Manuel Masías | Aprobada | [Abrir]
    }
    ====
    <color:green><b>✓ Notificación enviada al Admin</b></color>
    ====
    [ <b>Volver al programa</b> ]
}
@endsalt
