@startuml editarGrado

skinparam linetype polyline

state GRADO_ABIERTO
state GRADO_ABIERTO_SALIDA as "GRADO_ABIERTO"

GRADO_ABIERTO -[#green]-> editarGrado
note on link
<b>Admin</b> solicita editar Grado
end note

state editarGrado as "editarGrado()" {

    state " " as EditandoDatos

    [*] -[#green]-> EditandoDatos
    note on link
    <b>Sistema</b> presenta datos actuales del Grado
    <b>Sistema</b> muestra código
    <b>Sistema</b> permite solicitar guardar
    end note

    EditandoDatos -[#green]-> [*]
    note on link
    <b>Admin</b> introduce nombre
    <b>Admin</b> solicita guardar
    end note
}

editarGrado -[#green]-> GRADO_ABIERTO_SALIDA

@enduml
