@startsalt abrirUniversidades-wireframe
{
    <b>UNIVERSIDADES</b>
    ====
    {#
        <b>Nombre | <b>Facultades | .
        Universidad Europea del Atlántico (UNEATLANTICO) | 3 | [Abrir]
    }
    ====
    [ <b>+ Crear Universidad</b> ]
}
@endsalt
