@startsalt abrirReferenciaBibliografica-wireframe
{
    <b>REFERENCIA BIBLIOGRÁFICA</b>
    ====
    <b>Tipo:</b> Básica
    <b>Referencia:</b>
    "Sedgewick, R. (2008) Introduction to programming in Java,
    An interdisciplinary approach Ed. Pearson"
    ====
    {[Editar] | [Volver al listado]}
}
@endsalt
