@startsalt abrirGrados-wireframe
{
    <b>GRADOS -- ESCUELA POLITÉCNICA SUPERIOR</b>
    ====
    {#
        <b>Código | <b>Nombre | <b>Estado | . | .
        GII | Grado en Ingeniería Informática | Vigente | [Abrir] | [Eliminar]
        GIOI | Grado en Ingeniería de Organización Industrial | Vigente | [Abrir] | [Eliminar]
        GIIAA | Grado en Ingeniería de las Industrias Agrarias y Alimentarias | Vigente | [Abrir] | [Eliminar]
    }
    ====
    [ <b>+ Crear Grado</b> ]
}
@endsalt
