@startsalt editarPrograma-wireframe
{
    <b>EDITAR PROGRAMA</b>
    ====
    {
        <b>Código:</b> GII
        <b>Nombre (*):</b>
        "Grado en Ingeniería Informática"
        --
        <i>(*) Campo obligatorio</i>
        <i>El código no es editable una vez creado el Programa</i>
    }
    ~~
    {[Guardar]}
}
@endsalt
