@startuml eliminarReferenciaBibliografica

skinparam linetype polyline

state REFERENCIAS_BIBLIOGRAFICAS_ABIERTO
state REFERENCIAS_BIBLIOGRAFICAS_ABIERTOS_SALIDA as "REFERENCIAS_BIBLIOGRAFICAS_ABIERTO"

REFERENCIAS_BIBLIOGRAFICAS_ABIERTO -[#green]-> eliminarReferenciaBibliografica
note on link
<b>Profesor</b> solicita eliminar ReferenciaBibliografica
end note

state eliminarReferenciaBibliografica as "eliminarReferenciaBibliografica()" {

    state " " as ConfirmandoEliminacion

    [*] -[#green]-> ConfirmandoEliminacion
    note on link
    <b>Sistema</b> presenta información de la ReferenciaBibliografica
    <b>Sistema</b> permite solicitar confirmar/cancelar eliminación
    end note

    ConfirmandoEliminacion -[#green]-> [*]
    note on link
    <b>Profesor</b> solicita confirmar eliminación
    end note

    ConfirmandoEliminacion -[#blue]-> [*]
    note on link
    <b>Profesor</b> solicita cancelar eliminación
    end note
}

eliminarReferenciaBibliografica -[#green]-> REFERENCIAS_BIBLIOGRAFICAS_ABIERTOS_SALIDA
note on link
eliminada en memoria, lista actualizada
end note

eliminarReferenciaBibliografica -[#blue]-> REFERENCIAS_BIBLIOGRAFICAS_ABIERTOS_SALIDA
note on link
cancelada, sin cambios
end note

@enduml
