@startuml aprobarGuia

skinparam linetype polyline

state GUIA_ABIERTO
state GUIAS_DEL_GRADO_ABIERTOS_SALIDA as "GUIAS_DEL_GRADO_ABIERTO"

GUIA_ABIERTO -[#green]-> aprobarGuia
note on link
<b>DirectorGrado</b> solicita aprobar Guia
end note

state aprobarGuia as "aprobarGuia()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta Guia aprobada
    end note
}

aprobarGuia -[#green]-> GUIAS_DEL_GRADO_ABIERTOS_SALIDA
note on link
EnRevision -> Aprobada; registra "aprobada sin incidencia" en HistorialCambio
end note

@enduml
