@startuml crearGrado-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":GRADOS_ABIERTO" as GradosAbierto
rectangle #CDEBA5 ":GRADOS_ABIERTO" as GradosAbiertoSalida
rectangle #CDEBA5 ":Collaboration EditarGrado" as EditarGrado

package crearGrado as "crearGrado()" {
    rectangle #629EF9 CrearGradoView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E Grado
    rectangle #F2AC4E GradoRepository
}

GradosAbierto --> CrearGradoView: <font size=8>crearGrado()

CrearGradoView --> GradoController: <font size=8>validarDatosObligatorios(codigo, nombre) : boolean

CrearGradoView --> GradoController: <font size=8>crearGrado(codigo, nombre) : Grado

GradoController --> GradoRepository: <font size=8>existeCodigo(codigo) : boolean

GradoController --> GradoRepository: <font size=8>crear(codigo, nombre) : Grado

GradoRepository -- Grado

CrearGradoView ..[#green]> EditarGrado:<font size=8> <<include>> editarGrado()
CrearGradoView ..[#red]> GradosAbiertoSalida:<font size=8> código ya existente (issue #148), sin crear

@enduml
