@startuml abrirActividadesFormativas

skinparam linetype polyline

state SISTEMA_DISPONIBLE
state ACTIVIDADES_FORMATIVAS_ABIERTO

SISTEMA_DISPONIBLE -[#green]-> abrirActividadesFormativas
note on link
<b>Admin</b> solicita abrir Actividades Docentes
end note

state abrirActividadesFormativas as "abrirActividadesFormativas()" {

    state " " as ListandoCatalogo

    [*] -[#green]-> ListandoCatalogo
    note on link
    <b>Sistema</b> presenta selector de Universidad
    <b>Sistema</b> presenta listado de ActividadFormativa de la Universidad seleccionada
    end note

    ListandoCatalogo -[#green]-> [*]
    note on link
    <b>Admin</b> elige Universidad
    end note
}

abrirActividadesFormativas -[#green]-> ACTIVIDADES_FORMATIVAS_ABIERTO

@enduml
