@startsalt consultarEstadoGuias-wireframe
{
    <b>GUÍAS DEL PROGRAMA -- GII</b>
    ====
    [ <b>Notificar guías actualizadas</b> ]
    ====
    {#
        <b>AsignaturaPrograma | <b>Profesorado | <b>Estado | <b>Última actualización | .
        Programación I | Dr. Manuel Masías, Dr. Pablo Herrero | [ En revisión ] ámbar | Administración, hace dos días | [Abrir]
    }
    <b>Leyenda de estado:</b> [ Borrador ] neutro   [ En revisión ] ámbar   [ Aprobada ] verde   [ Rechazada ] rojo
}
@endsalt

@startsalt consultarEstadoGuias-wireframe-admin
{
    <b>GUÍAS DEL PROGRAMA -- GII (curso actual)</b>
    ====
    {#
        <b>AsignaturaPrograma | <b>Profesorado | <b>Estado | <b>Última actualización | . | .
        Programación I | Dr. Manuel Masías | [ Aprobada ] verde | Administración, hace dos días | [Previsualizar] | [Descargar PDF]
        Cálculo I | Dra. Paz Gutiérrez | [ Borrador ] neutro | Profesor, hace cinco días | [Previsualizar] | [Descargar PDF] !!disabled
    }
    <b>Leyenda de estado:</b> [ Borrador ] neutro   [ En revisión ] ámbar   [ Aprobada ] verde   [ Rechazada ] rojo
}
@endsalt
