@startuml editarGrado-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":GRADO_ABIERTO" as GradoAbierto
rectangle #CDEBA5 ":GRADO_ABIERTO" as GradoAbiertoSalida

package editarGrado as "editarGrado()" {
    rectangle #629EF9 EditarGradoView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E Grado
    rectangle #F2AC4E GradoRepository
}

GradoAbierto --> EditarGradoView: <font size=8>editarGrado(gradoId)

EditarGradoView --> GradoController: <font size=8>cargarGrado(gradoId) : Grado

GradoController --> GradoRepository: <font size=8>obtener(gradoId) : Grado

EditarGradoView --> GradoController: <font size=8>validarDatosObligatorios(codigo, nombre) : boolean

EditarGradoView --> GradoController: <font size=8>guardarCambios(gradoId, nombre) : boolean

GradoController --> Grado: <font size=8>actualizar(nombre)

GradoController --> GradoRepository: <font size=8>actualizar(grado)

GradoRepository -- Grado

EditarGradoView --> GradoAbiertoSalida: <font size=8>datos actualizados

@enduml
