@startsalt abrirUniversidad-wireframe
{
    <b>UNIVERSIDAD EUROPEA DEL ATLÁNTICO</b>
    ====
    <b>Nombre:</b> Universidad Europea del Atlántico (UNEATLANTICO)
    ====
    {[Editar] | [Volver al listado]}
}
@endsalt
