@startsalt abrirResultadosAprendizaje-wireframe
{
    <b>RESULTADOS DE APRENDIZAJE -- PROGRAMA EN INGENIERÍA INFORMÁTICA</b>
    ====
    {#
        <b>Código | <b>Tipo | <b>Descripción | <b>Asignaturas | . | .
        RAK1 | Conocimientos o contenidos | Describir los conceptos fundamentales de álgebra lineal... | 3 | [Abrir] | [Eliminar]
        RAK2 | Conocimientos o contenidos | Describir la estructura, organización y arquitectura... | 2 | [Abrir] | [Eliminar]
        RAH1 | Habilidades o destrezas | Aplicar principios físicos y electrónicos en la... | 1 | [Abrir] | [Eliminar]
        RAH2 | Habilidades o destrezas | Aplicar métodos matemáticos avanzados en la... | 0 | [Abrir] | [Eliminar]
        RAC1 | Competencias o capacidades | Aplicar conceptos de economía, organización y... | 4 | [Abrir] | [Eliminar]
        RAC2 | Competencias o capacidades | Desarrollar sistemas informáticos, considerando... | 2 | [Abrir] | [Eliminar]
    }
    ====
    [ <b>+ Crear Resultado de Aprendizaje</b> ]
}
@endsalt
