@startsalt abrirMaterias-wireframe
{
    <b>MATERIAS</b>
    ====
    {#
        <b>Nombre | <b>Asignaturas | . | .
        Programación | 2 | [Abrir] | [Eliminar]
        Matemáticas | 3 | [Abrir] | [Eliminar]
        Bases de Datos | 2 | [Abrir] | [Eliminar]
        Ingeniería del Software | 1 | [Abrir] | [Eliminar]
    }
    ====
    [ <b>+ Crear Materia</b> ]
}
@endsalt
