@startuml abrirAsignaturasPrograma

skinparam linetype polyline

state PROGRAMA_ABIERTO
state ASIGNATURAS_PROGRAMA_ABIERTO

PROGRAMA_ABIERTO -[#green]-> abrirAsignaturasPrograma
note on link
<b>DirectorPrograma</b> solicita abrir AsignaturasPrograma
end note

state abrirAsignaturasPrograma as "abrirAsignaturasPrograma()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta listado de AsignaturaPrograma del Programa
    end note
}

abrirAsignaturasPrograma -[#green]-> ASIGNATURAS_PROGRAMA_ABIERTO

@enduml
