@startsalt abrirAsignaturasPrograma-wireframe
{
    <b>ASIGNATURAS -- PROGRAMA EN INGENIERÍA INFORMÁTICA</b>
    ====
    {#
    <b>Asignatura                          | <b>Materia    | <b>Curso  | <b>Carácter | <b>Profesorado      |<b>Estado| .
    Programación I                         | Programación  | 1         | Básica | Dr. Manuel Masías        |[ Borrador ] neutro| [Abrir]
    Estructuras de datos y algoritmos I    | Programación  | 2         | Obligatoria | Dr. Manuel Masías   |[ En revisión ] ámbar| [Abrir]
    Redes de Ordenadores                   | Redes         | 2         | Obligatoria | Dr. Mariano Benito Hoz |[ Rechazada ] rojo| [Abrir]
    Ingeniería de Software I               | IdSw          | 3         | Obligatoria | Dr. Manuel Masías   |[ Aprobada ] verde| [Abrir]

    }
    <b>Leyenda de estado:</b> [ Borrador ] neutro   [ En revisión ] ámbar   [ Aprobada ] verde   [ Rechazada ] rojo
}
@endsalt

@startsalt abrirAsignaturasPrograma-wireframe-porProfesor
{
    <b>MIS ASIGNATURAS -- PROGRAMA EN INGENIERÍA INFORMÁTICA</b>
    ====
    {#
    <b>Asignatura                          | <b>Código | <b>Programa                          | <b>Curso |<b>Carácter |<b>Estado| .
    Programación I                         | IYA003 | Grado en Ingeniería Informática    | I-s1 | Básica |[ Borrador ] neutro| [Abrir]
    Ingeniería de Software I               | IYA038 | Grado en Ingeniería Informática    | III-s1 | Obligatoria |[ Aprobada ] verde| [Abrir]
    Estructuras de datos y algoritmos I    | IYA025 | Grado en Ingeniería Informática    | II-s1 | Obligatoria |[ En revisión ] ámbar| [Abrir]

    }
    <b>Leyenda de estado:</b> [ Borrador ] neutro   [ En revisión ] ámbar   [ Aprobada ] verde   [ Rechazada ] rojo
}
@endsalt
