@startsalt guardarBorradorGuia-wireframe
{
    <b>GUÍA DOCENTE -- Programación I (GII)</b>
    ====
    <color:green><b>✓ BORRADOR GUARDADO</b></color>
    ====
    <b>Estado:</b> Borrador
    <b>Fecha de última modificación:</b> 07/08/2026
    ====
    <i>Los cambios quedan guardados. Si la guía estaba Aprobada, vuelve a quedar en Borrador para que puedas terminar la corrección.</i>
    ====
    [ <b>Seguir editando</b> ]
}
@endsalt
