@startuml editarSesion-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":PLANIFICACION_DOCENTE_ABIERTO" as PlanificacionDocenteAbierto
rectangle #CDEBA5 ":PLANIFICACION_DOCENTE_ABIERTO" as PlanificacionDocenteSalida

package editarSesion as "editarSesion()" {
    rectangle #629EF9 EditarSesionView
    rectangle #b5bd68 PlanificacionDocenteController
    rectangle #F2AC4E Sesion
    rectangle #F2AC4E SesionRepository
}

PlanificacionDocenteAbierto --> EditarSesionView: <font size=8>editarSesion(sesionId)

EditarSesionView --> PlanificacionDocenteController: <font size=8>cargarSesion(sesionId) : Sesion

PlanificacionDocenteController --> SesionRepository: <font size=8>obtener(sesionId) : Sesion

EditarSesionView --> PlanificacionDocenteController: <font size=8>validarDatosObligatorios(tipo, descripcion) : boolean

EditarSesionView --> PlanificacionDocenteController: <font size=8>guardarCambios(tipo, descripcion) : boolean

PlanificacionDocenteController --> Sesion: <font size=8>actualizar(tipo, descripcion)

PlanificacionDocenteController --> SesionRepository: <font size=8>actualizar(sesion)

SesionRepository -- Sesion

EditarSesionView --> PlanificacionDocenteSalida: <font size=8>datos actualizados, número sin cambios

@enduml
