@startuml asociarResultadoAprendizajeAAsignaturaPrograma-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":ASIGNATURA_PROGRAMA_ABIERTO" as AsignaturaProgramaAbierto
rectangle #CDEBA5 ":ASIGNATURA_PROGRAMA_ABIERTO" as AsignaturaProgramaAbiertoSalida

package asociarResultadoAprendizajeAAsignaturaPrograma as "asociarResultadoAprendizajeAAsignaturaPrograma()" {
    rectangle #629EF9 AsociarResultadoAprendizajeAAsignaturaProgramaView
    rectangle #b5bd68 AsignaturaProgramaController
    rectangle #F2AC4E AsignaturaPrograma
    rectangle #F2AC4E AsignaturaProgramaRepository
    rectangle #F2AC4E ResultadoAprendizaje
    rectangle #F2AC4E ResultadoAprendizajeRepository
}

AsignaturaProgramaAbierto --> AsociarResultadoAprendizajeAAsignaturaProgramaView: <font size=8>asociarResultadoAprendizajeAAsignaturaPrograma(asignaturaProgramaId)

AsociarResultadoAprendizajeAAsignaturaProgramaView --> AsignaturaProgramaController: <font size=8>cargarResultadosAprendizajeDisponibles(asignaturaProgramaId) : List<ResultadoAprendizaje>

AsignaturaProgramaController --> ResultadoAprendizajeRepository: <font size=8>listarDisponiblesParaAsignaturaPrograma(asignaturaProgramaId) : List<ResultadoAprendizaje>

AsociarResultadoAprendizajeAAsignaturaProgramaView --> AsignaturaProgramaController: <font size=8>asociarResultadoAprendizaje(asignaturaProgramaId, resultadoAprendizajeId)

AsignaturaProgramaController --> AsignaturaProgramaRepository: <font size=8>asociarResultadoAprendizaje(asignaturaProgramaId, resultadoAprendizajeId)

ResultadoAprendizajeRepository -- ResultadoAprendizaje
AsignaturaProgramaRepository -- AsignaturaPrograma
AsignaturaPrograma -- ResultadoAprendizaje

AsociarResultadoAprendizajeAAsignaturaProgramaView --> AsignaturaProgramaAbiertoSalida: <font size=8>ResultadoAprendizaje asociado

@enduml
