@startuml asociarMetodologiaDocenteAAsignaturaGrado

skinparam linetype polyline

state ASIGNATURA_GRADO_ABIERTO
state ASIGNATURA_GRADO_ABIERTO_SALIDA as "ASIGNATURA_GRADO_ABIERTO"

ASIGNATURA_GRADO_ABIERTO -[#green]-> asociarMetodologiaDocenteAAsignaturaGrado
note on link
<b>DirectorGrado</b> solicita asociar MetodologiaDocente a AsignaturaGrado
end note

state asociarMetodologiaDocenteAAsignaturaGrado as "asociarMetodologiaDocenteAAsignaturaGrado()" {

    state " " as SolicitandoDatos

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Sistema</b> presenta selección de MetodologiaDocente ya asociadas a la Materia y no asociadas aún a esta AsignaturaGrado
    <b>Sistema</b> permite solicitar asociar
    end note

    SolicitandoDatos -[#green]-> [*]
    note on link
    <b>DirectorGrado</b> selecciona MetodologiaDocente
    <b>DirectorGrado</b> solicita asociar
    end note
}

asociarMetodologiaDocenteAAsignaturaGrado -[#green]-> ASIGNATURA_GRADO_ABIERTO_SALIDA

@enduml
