@startsalt descargarGuiaPDF-wireframe
{
    <b>GUÍA DOCENTE -- Programación I (GII)</b>
    ====
    <b>Fecha de generación de PDF:</b> 08/08/2026
    ====
    { "GII__IYA003 -- Programación I.pdf" }
    ====
    [ <b>Volver a la guía</b> ]
}
@endsalt
