@startuml crearGrado

skinparam linetype polyline

state GRADOS_ABIERTO
state GRADO_ABIERTO

GRADOS_ABIERTO -[#green]-> crearGrado
note on link
<b>Admin</b> solicita crear Grado
end note

state crearGrado as "crearGrado()" {

    state " " as SolicitandoDatos
    state c <<choice>>

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Sistema</b> presenta solicitud de datos mínimos del Grado
    <b>Sistema</b> permite solicitar crear
    end note

    SolicitandoDatos -[#green]-> c
    note on link
    <b>Admin</b> introduce código
    <b>Admin</b> introduce nombre
    <b>Admin</b> solicita crear
    end note

    c -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta Grado creado
    end note

    c -[#red]-> [*]
    note on link
    <b>Sistema</b> presenta mensaje de código ya existente
    end note
}

crearGrado -[#green]-> GRADO_ABIERTO
note on link
editarGrado()
end note

crearGrado -[#red]-> GRADOS_ABIERTO
note on link
código ya existente (issue #148), sin crear
end note

@enduml
