@startsalt abrirAsignatura-wireframe
{
    <b>PROGRAMACIÓN I</b>
    ====
    <b>Nombre:</b> Programación I
    <b>ECTS:</b> 6
    <b>Estado:</b> Vigente
    <b>Contenido:</b>
    "Introducción a la programación estructurada: variables, control
    de flujo, funciones, estructuras de datos básicas y depuración."
    ====
    <b>Presente en:</b>
    {#
        <b>Programa | <b>Materia | <b>Curso | <b>Carácter
        GII -- Grado en Ingeniería Informática | Programación | I-s1 | Básica
        GADE -- Grado en Administración y Dirección de Empresas | Informática Aplicada | III-s1 | Optativa
    }
    ====
    {[Editar] | [Volver al listado]}
}
@endsalt

@startsalt abrirAsignatura-wireframe-sinProgramas
{
    <b>ASIGNATURA NUEVA SIN INSTANCIAR</b>
    ====
    <b>Nombre:</b> Asignatura Nueva Sin Instanciar
    <b>ECTS:</b> --
    <b>Estado:</b> Vigente
    <b>Contenido:</b>
    --
    ====
    <b>Presente en:</b>
    Esta Asignatura no está en ningún Programa todavía.
    ====
    {[Editar] | [Volver al listado]}
}
@endsalt
