@startuml abrirPanelAdministracion-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":SISTEMA_DISPONIBLE" as SistemaDisponible
rectangle #CDEBA5 ":UNIVERSIDADES_ABIERTO" as UniversidadesAbierto
rectangle #CDEBA5 ":ASIGNATURAS_ABIERTO" as AsignaturasAbierto
rectangle #CDEBA5 ":METODOLOGIAS_DOCENTES_ABIERTO" as MetodologiasDocentesAbierto
rectangle #CDEBA5 ":PROFESORES_ABIERTO" as ProfesoresAbierto
rectangle #CDEBA5 ":CURSOS_ACADEMICOS_ABIERTO" as CursosAcademicosAbierto
rectangle #CDEBA5 ":SISTEMA_DISPONIBLE" as SistemaDisponibleSalida

package abrirPanelAdministracion as "abrirPanelAdministracion()" {
    rectangle #629EF9 AbrirPanelAdministracionView
}

SistemaDisponible --> AbrirPanelAdministracionView: <font size=8>abrirPanelAdministracion()

AbrirPanelAdministracionView --> UniversidadesAbierto: <font size=8>abrirUniversidades()
AbrirPanelAdministracionView --> AsignaturasAbierto: <font size=8>abrirAsignaturas()
AbrirPanelAdministracionView --> MetodologiasDocentesAbierto: <font size=8>abrirMetodologiasDocentes()
AbrirPanelAdministracionView --> ProfesoresAbierto: <font size=8>abrirProfesores()
AbrirPanelAdministracionView --> CursosAcademicosAbierto: <font size=8>abrirCursosAcademicos()
AbrirPanelAdministracionView --> SistemaDisponibleSalida: <font size=8>generarGuiasPDF() (self-loop)

@enduml
