@startsalt crearMetodologiaDocente-wireframe
{
    <b>CREAR METODOLOGÍA DOCENTE</b>
    ====
    {
        <b>Universidad (*):</b>
        ^Universidad Europea del Atlántico (UNEATLANTICO)^
        <b>Código (*):</b>
        "          "
        <b>Descripción (*):</b>
        "                                                  "
        --
        <i>(*) Campo obligatorio</i>
    }
    ~~
    {[Crear]}
}
@endsalt
