@startuml editarSesion

skinparam linetype polyline

state PLANIFICACION_DOCENTE_ABIERTO
state PLANIFICACION_DOCENTE_ABIERTO_SALIDA as "PLANIFICACION_DOCENTE_ABIERTO"

PLANIFICACION_DOCENTE_ABIERTO -[#green]-> editarSesion
note on link
<b>Profesor</b> solicita editar Sesion de la Planificación docente
end note

state editarSesion as "editarSesion()" {

    state " " as EditandoDatos

    [*] -[#green]-> EditandoDatos
    note on link
    <b>Sistema</b> presenta datos actuales de la sesión
    <b>Sistema</b> presenta selección de tipo
    <b>Sistema</b> permite solicitar guardar
    end note

    EditandoDatos -[#green]-> [*]
    note on link
    <b>Profesor</b> selecciona tipo
    <b>Profesor</b> introduce descripción
    <b>Profesor</b> solicita guardar
    end note
}

editarSesion -[#green]-> PLANIFICACION_DOCENTE_ABIERTO_SALIDA
note on link
datos actualizados, número sin cambios
end note

@enduml
