@startsalt editarActividadFormativa-wireframe
{
    <b>EDITAR ACTIVIDAD FORMATIVA</b>
    ====
    {
        <b>Código:</b> AF3
        <b>Nombre (*):</b>
        "Clases prácticas (laboratorio)"
        --
        <i>(*) Campo obligatorio</i>
        <i>El código no es editable una vez creada la actividad</i>
    }
    ~~
    {[Guardar]}
}
@endsalt
