@startuml editarActividadesFormativasMateria

skinparam linetype polyline

state MATERIA_ABIERTO
state MATERIA_ABIERTO_SALIDA as "MATERIA_ABIERTO"

MATERIA_ABIERTO -[#green]-> editarActividadesFormativasMateria
note on link
<b>DirectorGrado</b> solicita editar las actividades formativas de la Materia
end note

state editarActividadesFormativasMateria as "editarActividadesFormativasMateria()" {

    state " " as EditandoReparto
    state c <<choice>>

    [*] -[#green]-> EditandoReparto
    note on link
    <b>Sistema</b> presenta las 10 actividades formativas con sus horas actuales
    <b>Sistema</b> permite solicitar guardar
    end note

    EditandoReparto -[#green]-> c
    note on link
    <b>DirectorGrado</b> introduce las horas de cada actividad formativa
    <b>DirectorGrado</b> solicita guardar
    end note

    c -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta el reparto guardado
    end note

    c -[#red]-> [*]
    note on link
    <b>Sistema</b> presenta mensaje de horas no válidas (valor negativo)
    end note
}

editarActividadesFormativasMateria -[#green]-> MATERIA_ABIERTO_SALIDA

editarActividadesFormativasMateria -[#red]-> MATERIA_ABIERTO_SALIDA
note on link
algún valor de horas no válido, no se guarda nada
end note

@enduml
