@startuml abrirProgramas

skinparam linetype polyline

state FACULTAD_ABIERTO
state PROGRAMAS_ABIERTO

FACULTAD_ABIERTO -[#green]-> abrirProgramas
note on link
<b>Admin</b> solicita abrir Programas
end note

state abrirProgramas as "abrirProgramas()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta listado de Programas
    end note
}

abrirProgramas -[#green]-> PROGRAMAS_ABIERTO

@enduml
