@startuml crearSistemaEvaluacion

skinparam linetype polyline

state SISTEMAS_EVALUACION_ABIERTO
state SISTEMA_EVALUACION_ABIERTO

SISTEMAS_EVALUACION_ABIERTO -[#green]-> crearSistemaEvaluacion
note on link
<b>Admin</b> solicita crear SistemaEvaluacion
end note

state crearSistemaEvaluacion as "crearSistemaEvaluacion()" {

    state " " as SolicitandoDatos

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Sistema</b> presenta solicitud de datos del sistema de evaluación
    <b>Sistema</b> muestra tipo
    <b>Sistema</b> muestra descripción
    <b>Sistema</b> muestra ponderación mínima
    <b>Sistema</b> muestra ponderación máxima
    <b>Sistema</b> permite solicitar crear
    end note

    SolicitandoDatos -[#green]-> [*]
    note on link
    <b>Admin</b> introduce tipo
    <b>Admin</b> introduce descripción
    <b>Admin</b> introduce ponderación mínima
    <b>Admin</b> introduce ponderación máxima
    <b>Admin</b> solicita crear
    end note
}

crearSistemaEvaluacion -[#green]-> SISTEMA_EVALUACION_ABIERTO
note on link
editarSistemaEvaluacion()
end note

@enduml
