@startsalt definirDirectorPrograma-wireframe
{
    <b>NOMBRAR DIRECTOR DE PROGRAMA -- DR. JON ARAMBARRI BASAÑEZ</b>
    ====
    {
        <b>Programa (*):</b>
        ^GII -- Grado en Ingeniería Informática^
        --
        <i>(*) Campo obligatorio</i>
        <i>Solo se listan los Programas que el Profesor todavía no dirige</i>
    }
    ~~
    {[Nombrar]}
}
@endsalt

@startsalt definirDirectorPrograma-wireframe-desdePrograma
{
    <b>GII -- PROGRAMA EN INGENIERÍA INFORMÁTICA</b>
    ====
    <b>Directores:</b>
    {
        Dr. Manuel Masías Vergara (manuel.masias@uneatlantico.es) | [Quitar]
    }
    ====
    {
        ^Dr. Jon Arambarri Basañez^ | [Nombrar]
    }
    <i>Solo se listan los Profesores que todavía no dirigen este Programa</i>
}
@endsalt
