@startuml eliminarPrograma-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":PROGRAMAS_ABIERTO" as ProgramasAbierto
rectangle #CDEBA5 ":PROGRAMAS_ABIERTO" as ProgramasAbiertoSalida

package eliminarPrograma as "eliminarPrograma()" {
    rectangle #629EF9 EliminarProgramaView
    rectangle #b5bd68 ProgramaController
    rectangle #F2AC4E Programa
    rectangle #F2AC4E ProgramaRepository
}

ProgramasAbierto --> EliminarProgramaView: <font size=8>eliminarPrograma(programaId)

EliminarProgramaView --> ProgramaController: <font size=8>eliminar(programaId)

ProgramaController --> Programa: <font size=8>extinguir()

ProgramaController --> ProgramaRepository: <font size=8>actualizar(programa)

ProgramaRepository -- Programa

EliminarProgramaView ..[#green]> ProgramasAbiertoSalida: <font size=8>lista actualizada -- estado pasa a Extinguido
EliminarProgramaView ..[#blue]> ProgramasAbiertoSalida: <font size=8>cancelada, sin cambios

@enduml
