@startuml asociarMetodologiaDocenteAPrograma-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":METODOLOGIAS_DOCENTES_PROGRAMA_ABIERTO" as MetodologiasDocentesAbierto
rectangle #CDEBA5 ":METODOLOGIAS_DOCENTES_PROGRAMA_ABIERTO" as MetodologiasDocentesAbiertoSalida

package asociarMetodologiaDocenteAPrograma as "asociarMetodologiaDocenteAPrograma()" {
    rectangle #629EF9 AsociarMetodologiaDocenteAProgramaView
    rectangle #b5bd68 ProgramaController
    rectangle #F2AC4E Programa
    rectangle #F2AC4E ProgramaRepository
    rectangle #F2AC4E MetodologiaDocente
    rectangle #F2AC4E MetodologiaDocenteRepository
}

MetodologiasDocentesAbierto --> AsociarMetodologiaDocenteAProgramaView: <font size=8>asociarMetodologiaDocenteAPrograma(programaId)

AsociarMetodologiaDocenteAProgramaView --> ProgramaController: <font size=8>cargarMetodologiasDocentesDisponibles(programaId) : List<MetodologiaDocente>

ProgramaController --> MetodologiaDocenteRepository: <font size=8>listarDisponiblesParaPrograma(programaId) : List<MetodologiaDocente>

AsociarMetodologiaDocenteAProgramaView --> ProgramaController: <font size=8>asociarMetodologiaDocente(programaId, metodologiaDocenteId)

ProgramaController --> ProgramaRepository: <font size=8>asociarMetodologiaDocente(programaId, metodologiaDocenteId)

MetodologiaDocenteRepository -- MetodologiaDocente
ProgramaRepository -- Programa
Programa -- MetodologiaDocente

AsociarMetodologiaDocenteAProgramaView --> MetodologiasDocentesAbiertoSalida: <font size=8>MetodologiaDocente asociada

@enduml
