@startuml asociarResultadoAprendizajeAAsignaturaGrado-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbierto
rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbiertoSalida

package asociarResultadoAprendizajeAAsignaturaGrado as "asociarResultadoAprendizajeAAsignaturaGrado()" {
    rectangle #629EF9 AsociarResultadoAprendizajeAAsignaturaGradoView
    rectangle #b5bd68 AsignaturaGradoController
    rectangle #F2AC4E AsignaturaGrado
    rectangle #F2AC4E AsignaturaGradoRepository
    rectangle #F2AC4E ResultadoAprendizaje
    rectangle #F2AC4E ResultadoAprendizajeRepository
}

AsignaturaGradoAbierto --> AsociarResultadoAprendizajeAAsignaturaGradoView: <font size=8>asociarResultadoAprendizajeAAsignaturaGrado(asignaturaGradoId)

AsociarResultadoAprendizajeAAsignaturaGradoView --> AsignaturaGradoController: <font size=8>cargarResultadosAprendizajeDisponibles(asignaturaGradoId) : List<ResultadoAprendizaje>

AsignaturaGradoController --> ResultadoAprendizajeRepository: <font size=8>listarDisponiblesParaAsignaturaGrado(asignaturaGradoId) : List<ResultadoAprendizaje>

AsociarResultadoAprendizajeAAsignaturaGradoView --> AsignaturaGradoController: <font size=8>asociarResultadoAprendizaje(asignaturaGradoId, resultadoAprendizajeId)

AsignaturaGradoController --> AsignaturaGradoRepository: <font size=8>asociarResultadoAprendizaje(asignaturaGradoId, resultadoAprendizajeId)

ResultadoAprendizajeRepository -- ResultadoAprendizaje
AsignaturaGradoRepository -- AsignaturaGrado
AsignaturaGrado -- ResultadoAprendizaje

AsociarResultadoAprendizajeAAsignaturaGradoView --> AsignaturaGradoAbiertoSalida: <font size=8>ResultadoAprendizaje asociado

@enduml
