@startuml asignarProfesorAAsignaturaPrograma

skinparam linetype polyline

state ASIGNATURA_PROGRAMA_ABIERTO
state ASIGNATURA_PROGRAMA_ABIERTO_SALIDA as "ASIGNATURA_PROGRAMA_ABIERTO"

ASIGNATURA_PROGRAMA_ABIERTO -[#green]-> asignarProfesorAAsignaturaPrograma
note on link
<b>Admin</b> solicita asignar Profesor a AsignaturaPrograma
end note

state asignarProfesorAAsignaturaPrograma as "asignarProfesorAAsignaturaPrograma()" {

    state " " as SolicitandoDatos

    [*] -[#green]-> SolicitandoDatos
    note on link
    <b>Sistema</b> presenta selección de Profesores no asignados aún a esta AsignaturaPrograma
    <b>Sistema</b> permite solicitar asignar
    end note

    SolicitandoDatos -[#green]-> [*]
    note on link
    <b>Admin</b> selecciona Profesor
    <b>Admin</b> solicita asignar
    end note
}

asignarProfesorAAsignaturaPrograma -[#green]-> ASIGNATURA_PROGRAMA_ABIERTO_SALIDA
note on link
<b>Sistema</b> presenta la lista de Profesores actualizada
<b>Sistema</b> pasa la Guía activa a En revisión, si estaba Aprobada y la plantilla cambió de verdad, para que el director la re-apruebe
end note

@enduml
