@startuml comprobarCopiasSeguridad

skinparam linetype polyline

state COPIAS_SEGURIDAD_ABIERTO
state COPIAS_SEGURIDAD_ABIERTO_SALIDA as "COPIAS_SEGURIDAD_ABIERTO"

COPIAS_SEGURIDAD_ABIERTO -[#green]-> comprobarCopiasSeguridad
note on link
<b>Admin</b> solicita comprobar las copias de seguridad
end note

state comprobarCopiasSeguridad as "comprobarCopiasSeguridad()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta la salud de cada copia (correcta, dañada, ilegible o no disponible) y un resumen
    end note
}

comprobarCopiasSeguridad -[#green]-> COPIAS_SEGURIDAD_ABIERTO_SALIDA

@enduml
