@startsalt abrirMateria-wireframe
{
    <b>PROGRAMACIÓN</b>
    ====
    <b>Nombre:</b> Programación
    ====
    <b>Metodologías docentes asociadas:</b>
    {#
        <b>Código | <b>Descripción | <b>Descripción propia | . | .
        MD1 | Método expositivo | -- | [Editar] | [Quitar]
        MD5 | Aprendizaje orientado a proyectos | Incluye trabajo por sprints | [Editar] | [Quitar]
    }
    [ <b>+ Asociar Metodología Docente</b> ]
    ====
    <b>Resultados de aprendizaje asociados:</b>
    {#
        <b>Código | <b>Tipo | <b>Asignaturas | .
        RAK1 | Conocimientos o contenidos | 2 | [Quitar]
        RAH1 | Habilidades o destrezas | 0 | [Quitar]
    }
    [ <b>+ Asociar Resultado de Aprendizaje</b> ]
    ====
    <b>Asignaturas de esta materia:</b>
    {#
        <b>Asignatura | <b>Curso | <b>Carácter | .
        Programación I | I-s1 | Básica | [Abrir]
    }
    ====
    <b>Actividades formativas de la materia:</b>
    {#
        <b>Actividad formativa | <b>Horas materia | <b>Σ asignaturas | .
        Clases expositivas | 45 | 45 | OK
        Clases prácticas | 20 | 15 | discrepancia -5
        ... (las 10, siempre) | | |
    }
    [ <b>Editar reparto</b> ]  |  "Medidor AfM = ΣAfAdM (informativo, no bloquea)"
    ====
    {[Editar] | [Volver al listado]}
}
@endsalt
