@startuml editarAsignaturaGrado-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbierto
rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbiertoSalida

package editarAsignaturaGrado as "editarAsignaturaGrado()" {
    rectangle #629EF9 EditarAsignaturaGradoView
    rectangle #b5bd68 AsignaturaGradoController
    rectangle #F2AC4E AsignaturaGrado
    rectangle #F2AC4E AsignaturaGradoRepository
    rectangle #F2AC4E GuiaRepository
}

AsignaturaGradoAbierto --> EditarAsignaturaGradoView: <font size=8>editarAsignaturaGrado(asignaturaGradoId)

EditarAsignaturaGradoView --> AsignaturaGradoController: <font size=8>obtenerParaEditar(asignaturaGradoId)

AsignaturaGradoController --> AsignaturaGradoRepository: <font size=8>obtener(asignaturaGradoId) : AsignaturaGrado
AsignaturaGradoController --> GuiaRepository: <font size=8>existeAlgunaDe(asignaturaGradoId) : boolean

AsignaturaGradoController --> EditarAsignaturaGradoView: <font size=8>AsignaturaGrado, semestreDefaultBloqueado : boolean

EditarAsignaturaGradoView --> AsignaturaGradoController: <font size=8>guardarCambios(asignaturaGradoId, curso, caracter, idioma, semestreDefault, nombre, ects, contenido, requisitosPrevios) : AsignaturaGrado

AsignaturaGradoController --> AsignaturaGrado: <font size=8>actualizar(curso, caracter, idioma, semestreDefault, nombre, ects, contenido, requisitosPrevios)
note right: semestreDefault se aplica solo si\nsemestreDefaultBloqueado era false

AsignaturaGradoController --> AsignaturaGradoRepository: <font size=8>actualizar(asignaturaGrado) : AsignaturaGrado

AsignaturaGradoRepository -- AsignaturaGrado

EditarAsignaturaGradoView --> AsignaturaGradoAbiertoSalida: <font size=8>datos actualizados

@enduml
