@startuml abrirResultadoAprendizaje

skinparam linetype polyline

state RESULTADOS_APRENDIZAJE_ABIERTO
state RESULTADO_APRENDIZAJE_ABIERTO

RESULTADOS_APRENDIZAJE_ABIERTO -[#green]-> abrirResultadoAprendizaje
note on link
<b>DirectorGrado</b> solicita abrir resultado de aprendizaje
end note

state abrirResultadoAprendizaje as "abrirResultadoAprendizaje()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> muestra datos del resultado de aprendizaje
    end note
}

abrirResultadoAprendizaje -[#green]-> RESULTADO_APRENDIZAJE_ABIERTO

@enduml
