@startuml consultarCopiasSeguridad

skinparam linetype polyline

state SISTEMA_DISPONIBLE
state SISTEMA_DISPONIBLE_SALIDA as "SISTEMA_DISPONIBLE"

SISTEMA_DISPONIBLE -[#green]-> consultarCopiasSeguridad
note on link
<b>Admin</b> solicita consultar copias de seguridad
end note

state consultarCopiasSeguridad as "consultarCopiasSeguridad()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta listado de copias de seguridad, ordenado por fecha descendente
    end note
}

consultarCopiasSeguridad -[#green]-> SISTEMA_DISPONIBLE_SALIDA
note on link
abrirPanelAdministracion()
end note

@enduml
