@startsalt consultarCopiasSeguridad-wireframe
{
    <b>COPIAS DE SEGURIDAD</b>
    ====
    [ Volver al panel de administración ]
    ====
    {#
        <b>Familia | <b>Fecha | <b>Tamaño | <b>Motivo
        Puntual | 11/09/2026, 2:00:00 | 928.0 KB | deploy #307
        Diario  | 11/09/2026, 4:30:00 | 1.1 MB   | --
        Diario  | 10/09/2026, 4:30:00 | 921.7 KB | --
    }
}
@endsalt

@startsalt consultarCopiasSeguridad-wireframe-vacia
{
    <b>COPIAS DE SEGURIDAD</b>
    ====
    [ Volver al panel de administración ]
    ====
    <i>No hay copias de seguridad registradas todavía.</i>
}
@endsalt
