@startsalt editarResultadoAprendizaje-wireframe
{
    <b>EDITAR RESULTADO DE APRENDIZAJE</b>
    ====
    {
        <b>Código (*):</b>
        "RAK1"
        <b>Tipo (*):</b>
        ^Conocimientos o contenidos^
        <b>Descripción (*):</b>
        "Describir los conceptos fundamentales de álgebra lineal, cálculo
        diferencial e integral, métodos numéricos, algorítmica numérica,
        estadística y optimización relevantes para la ingeniería."
        --
        <i>(*) Campo obligatorio</i>
    }
    ~~
    {[Guardar]}
}
@endsalt
