@startuml revocarAprobacionGuia-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":GUIA_ABIERTO" as GuiaAbierto
rectangle #CDEBA5 ":GUIAS_DEL_GRADO_ABIERTO" as GuiasDelGradoSalida

package revocarAprobacionGuia as "revocarAprobacionGuia()" {
    rectangle #629EF9 RevocarAprobacionGuiaView
    rectangle #b5bd68 GuiaController
    rectangle #F2AC4E Guia
    rectangle #F2AC4E HistorialCambio
    rectangle #F2AC4E GuiaRepository
}

GuiaAbierto --> RevocarAprobacionGuiaView: <font size=8>revocarAprobacionGuia(guiaId, comentario)

RevocarAprobacionGuiaView --> GuiaController: <font size=8>revocarAprobacion(guiaId, comentario) : Guia

GuiaController --> Guia: <font size=8>revocarAprobacion() : boolean

GuiaController --> HistorialCambio: <font size=8>registrar("estado", "Aprobada", "Borrador", comentario) : HistorialCambio

GuiaController --> GuiaRepository: <font size=8>actualizar(guia) : Guia

Guia -- HistorialCambio
GuiaRepository -- Guia

RevocarAprobacionGuiaView ..[#green]> GuiasDelGradoSalida: <font size=8>aprobación revocada

@enduml
