@startsalt abrirReferenciasBibliograficas-wireframe
{
    <b>BIBLIOGRAFÍA -- Programación I (GII)</b>
    ====
    {#
        <b>Tipo | <b>Referencia | . | .
        Básica | Sedgewick, R. (2008) Introduction to programming in Java... | [Abrir] | [Eliminar]
        Básica | Streib, J. (2014) Guide to Java, A concise introduction... | [Abrir] | [Eliminar]
        Complementaria | Serbat, A (2016) Fundamentos de Programación con Java... | [Abrir] | [Eliminar]
        Complementaria | Sedgewick R. Algorithms, 4th Edition Ed. Pearson | [Abrir] | [Eliminar]
        Complementaria | Martin, R. (2011) The Clean Coder Ed. Prentice Hall | [Abrir] | [Eliminar]
        Webs de referencia | http://www.java.com/es/ | [Abrir] | [Eliminar]
        Webs de referencia | http://docs.oracle.com/javase/8/ | [Abrir] | [Eliminar]
        Webs de referencia | https://developers.google.com/blockly/ | [Abrir] | [Eliminar]
        Webs de referencia | http://introcs.cs.princeton.edu/java/home/ | [Abrir] | [Eliminar]
        Otras fuentes de consulta | https://github.com/mmasias/prg1 | [Abrir] | [Eliminar]
    }
    ====
    [ <b>+ Crear Referencia</b> ]
    ====
    {[Volver a la guía]}
}
@endsalt
