@startuml asociarMetodologiaDocenteAAsignaturaGrado-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbierto
rectangle #CDEBA5 ":ASIGNATURA_GRADO_ABIERTO" as AsignaturaGradoAbiertoSalida

package asociarMetodologiaDocenteAAsignaturaGrado as "asociarMetodologiaDocenteAAsignaturaGrado()" {
    rectangle #629EF9 AsociarMetodologiaDocenteAAsignaturaGradoView
    rectangle #b5bd68 AsignaturaGradoController
    rectangle #F2AC4E AsignaturaGrado
    rectangle #F2AC4E AsignaturaGradoRepository
    rectangle #F2AC4E MetodologiaDocente
    rectangle #F2AC4E MetodologiaDocenteRepository
}

AsignaturaGradoAbierto --> AsociarMetodologiaDocenteAAsignaturaGradoView: <font size=8>asociarMetodologiaDocenteAAsignaturaGrado(asignaturaGradoId)

AsociarMetodologiaDocenteAAsignaturaGradoView --> AsignaturaGradoController: <font size=8>cargarMetodologiasDocentesDisponibles(asignaturaGradoId) : List<MetodologiaDocente>

AsignaturaGradoController --> MetodologiaDocenteRepository: <font size=8>listarDisponiblesParaAsignaturaGrado(asignaturaGradoId) : List<MetodologiaDocente>

AsociarMetodologiaDocenteAAsignaturaGradoView --> AsignaturaGradoController: <font size=8>asociarMetodologiaDocente(asignaturaGradoId, metodologiaDocenteId)

AsignaturaGradoController --> AsignaturaGradoRepository: <font size=8>asociarMetodologiaDocente(asignaturaGradoId, metodologiaDocenteId)

MetodologiaDocenteRepository -- MetodologiaDocente
AsignaturaGradoRepository -- AsignaturaGrado
AsignaturaGrado -- MetodologiaDocente

AsociarMetodologiaDocenteAAsignaturaGradoView --> AsignaturaGradoAbiertoSalida: <font size=8>MetodologiaDocente asociada

@enduml
