@startuml modeloDominio

!theme plain
hide empty members
hide circle
skinparam linetype polyline
left to right direction

package "Estructura curricular" {
  class Universidad {
    nombre
  }
  class Facultad {
    nombre
  }
  class ProgramaPadre {
    nombre
  }
  class Programa {
    codigo
    nombre
    estado
  }
  class Materia {
    nombre
  }
  class SistemaEvaluacion {
    tipo
    descripcion
    ponderacionMinima
    ponderacionMaxima
  }
  class MetodologiaDocente {
    codigo
    descripcion
  }
  class MetodologiaMateria {
    descripcionPropia
  }
  class ActividadFormativa {
    codigo
    nombre
  }
  class ActividadFormativaMateria {
    horas
  }
  class ActividadFormativaAsignaturaPrograma {
    horas
    porcentajePresencialidad
  }
  class Asignatura {
    codigo
    nombre
    ects
    contenido
    estado
  }
  class AsignaturaPrograma {
    nombre
    curso
    caracter
    idioma
    ects
    semestreDefault
    contenido
    requisitosPrevios
    sesionesMinimas
    estado
  }
  class ResultadoAprendizaje {
    codigo
    tipo
    descripcion
  }
  class Requisito {
    tipo
  }
  class CursoAcademico {
    inicio
    fin
    estado
    semestreActivo
  }
  Universidad *-- Facultad
  Facultad *-- Programa
  ProgramaPadre o-- Programa
  Programa *-- Materia
  Programa o-- MetodologiaDocente
  Materia *-- AsignaturaPrograma
  Materia *-- SistemaEvaluacion
  Materia o-- MetodologiaDocente
  (Materia, MetodologiaDocente) .. MetodologiaMateria
  Universidad *-- MetodologiaDocente
  Universidad *-- ActividadFormativa
  Materia o-- ActividadFormativa
  (Materia, ActividadFormativa) .. ActividadFormativaMateria
  AsignaturaPrograma o-- ActividadFormativa
  (AsignaturaPrograma, ActividadFormativa) .. ActividadFormativaAsignaturaPrograma
  (Programa, Asignatura) .. AsignaturaPrograma
  Programa *-d- ResultadoAprendizaje
  Materia o-u- ResultadoAprendizaje
  AsignaturaPrograma o- ResultadoAprendizaje
  AsignaturaPrograma o-r- MetodologiaDocente
  AsignaturaPrograma -> AsignaturaPrograma : <sub>requiere</sub>
  'AsignaturaPrograma -[hidden]r- Requisito
  (AsignaturaPrograma, AsignaturaPrograma) .. Requisito
  Universidad -- CursoAcademico
}

package "Guía docente" {
  class Guia {
    semestre
    contenido
    estado
    sesionesMinimas
    fechaCreacion
    fechaUltimaModificacion
    fechaGeneracionPDF
  }
  class HistorialCambio {
    campo
    valorAnterior
    valorNuevo
    fecha
    comentario
  }

  class PonderacionEvaluacion {
    descripcion
    ponderacion
    vinculada
  }

  (AsignaturaPrograma, CursoAcademico) .. Guia
  Guia *- HistorialCambio
  Guia *-d- PonderacionEvaluacion
  PonderacionEvaluacion -> SistemaEvaluacion

  class ReferenciaBibliografica {
    tipo
    referencia
    vinculada
  }

  Guia *-- ReferenciaBibliografica

  class PlanificacionDocente
  class Sesion {
    numero
    tipo
    descripcion
    vinculada
  }

  Guia *-- PlanificacionDocente
  PlanificacionDocente *-- Sesion
}

package "Personas y roles" {
  class Actor
  class Profesor {
    nombre
    email
  }
  class Admin {
    email
  }
  class DirectorPrograma
  class PerfilProfesorCurso {
    validado
    orcid
    esDoctor
    universidadDoctorado
    anioDoctorado
    programaDoctorado
    mencionInternacional
    nivelAcreditacionSiiu
    organismoAcreditador
    organismoAcreditadorOtro
    numSexenios
    anioUltimoSexenio
    tramitandoSexenio
    numQuinquenios
    anioUltimoQuinquenio
    biografia
    aniosExperienciaDocente
    aniosExperienciaDocenteVirtual
    aniosExperienciaProfesional
    aniosExperienciaInvestigadora
    enlaceCvn
    enlaceFoto
    enlaceScholar
  }

  Profesor -u-|> Actor
  Admin -u-|> Actor
  DirectorPrograma -u-|> Profesor
  Actor -> HistorialCambio
  Universidad -- Profesor
  AsignaturaPrograma - Profesor
  Programa o- DirectorPrograma
  (Profesor, CursoAcademico) .. PerfilProfesorCurso
}

Guia -- Profesor

@enduml
