@startuml modeloDominioSimple

!theme plain
hide empty members
hide circle
skinparam linetype polyline
left to right direction


package "Estructura curricular" {
  class Universidad
  class Facultad
  class ProgramaPadre
  class Programa
  class Materia
  class SistemaEvaluacion
  class MetodologiaDocente
  class MetodologiaMateria
  class ActividadFormativa
  class ActividadFormativaMateria
  class ActividadFormativaAsignaturaPrograma
  class Asignatura
  class AsignaturaPrograma
  class ResultadoAprendizaje
  class Requisito
  class CursoAcademico

  Universidad *-- Facultad
  Facultad *-- Programa
  ProgramaPadre o-- Programa
  Programa *-- Materia
  Programa o-- MetodologiaDocente
  Materia *-- AsignaturaPrograma
  Materia *-- SistemaEvaluacion
  Materia o-- MetodologiaDocente
  (Materia, MetodologiaDocente) .. MetodologiaMateria
  Universidad *-- MetodologiaDocente
  Universidad *-- ActividadFormativa
  Materia o-- ActividadFormativa
  (Materia, ActividadFormativa) .. ActividadFormativaMateria
  AsignaturaPrograma o-- ActividadFormativa
  (AsignaturaPrograma, ActividadFormativa) .. ActividadFormativaAsignaturaPrograma
  (Programa, Asignatura) .. AsignaturaPrograma
  Programa *-d- ResultadoAprendizaje
  Materia o-u- ResultadoAprendizaje
  AsignaturaPrograma o- ResultadoAprendizaje
  AsignaturaPrograma o-r- MetodologiaDocente
  AsignaturaPrograma -> AsignaturaPrograma : <sub>requiere</sub>
  'AsignaturaPrograma -[hidden]r- Requisito
  (AsignaturaPrograma, AsignaturaPrograma) .. Requisito
  Universidad -- CursoAcademico
}

package "Personas y roles" {
  class Actor
  class Profesor
  class Admin
  class DirectorPrograma
  class PerfilProfesorCurso

  Profesor -u-|> Actor
  Admin -u-|> Actor
  DirectorPrograma -u-|> Profesor
  Actor -r-> HistorialCambio
  Universidad -- Profesor
  AsignaturaPrograma - Profesor
  Programa o- DirectorPrograma
  (Profesor, CursoAcademico) .. PerfilProfesorCurso
}


package "Guía docente" {
  class Guia
  class HistorialCambio
  class PonderacionEvaluacion
  (AsignaturaPrograma, CursoAcademico) .. Guia
  Guia *- HistorialCambio
  Guia *- PonderacionEvaluacion
  PonderacionEvaluacion -> SistemaEvaluacion
  class ReferenciaBibliografica
  Guia *-- ReferenciaBibliografica
  class PlanificacionDocente
  class Sesion
  Guia *-- PlanificacionDocente
  PlanificacionDocente *-- Sesion
}


Guia -- Profesor

@enduml
