@startsalt escalarGuiaAAprobada-wireframe
{
    <b>GUÍA DOCENTE -- Programación I (GII)</b>
    ====
    <color:green><b>✓ GUÍA ESCALADA A APROBADA</b></color>
    ====
    <b>Estado anterior:</b> Borrador
    <b>Estado actual:</b> Aprobada
    <b>Comentario registrado:</b> "Escalada a aprobada sin incidencia"
    ====
    [ <b>Volver al listado de guías</b> ]
}
@endsalt
