@startuml abrirInicio

skinparam linetype polyline

state SESION_CERRADA
state INICIO_ABIERTO

SESION_CERRADA -[#green]-> abrirInicio
note on link
tras validacion exitosa -- punto de extension de <b>iniciarSesion()</b>
end note

state abrirInicio as "abrirInicio()" {

    [*] -[#green]-> [*]
    note on link
    <b>Sistema</b> presenta la pantalla de inicio: seccion "Mis guias" si la
    cuenta es Profesor, seccion "Mis programas" si dirige algun Programa
    end note
}

abrirInicio -[#green]-> INICIO_ABIERTO

@enduml
