@startsalt abrirInicio-wireframe
{
    <b>INICIO</b>
    ====
    <b>Mis guías</b>
    Manual del profesor
    {#
    <b>Asignatura                          | <b>Programa                          | <b>Carácter    |<b>Estado    | .
    Programación I                         | Grado en Ingeniería Informática    | Básica         |Borrador     | [Abrir guía]
    Ingeniería de Software I               | Grado en Ingeniería Informática    | Obligatoria    |Aprobada     | [Abrir guía]
    Estructuras de datos y algoritmos I    | Grado en Ingeniería Informática    | Obligatoria    |En revisión  | [Abrir guía]
    }
    ====
    <b>Mis programas</b>
    Manual del director de programa
    {#
    <b>Nombre                          | <b>Código | <b>Estado | .
    Grado en Ingeniería Informática    | GII      | Vigente   | [Abrir]
    }
    ====
    [ Cerrar sesión ]
}
@endsalt
