@startuml editarProfesor-analisis
skinparam linetype polyline

left to right direction

rectangle #CDEBA5 ":PROFESOR_ABIERTO" as ProfesorAbierto
rectangle #CDEBA5 ":PROFESOR_ABIERTO" as ProfesorAbiertoSalida

package editarProfesor as "editarProfesor()" {
    rectangle #629EF9 EditarProfesorView
    rectangle #b5bd68 ProfesorController
    rectangle #F2AC4E Profesor
    rectangle #F2AC4E ProfesorRepository
}

ProfesorAbierto --> EditarProfesorView: <font size=8>editarProfesor(profesorId)

EditarProfesorView --> ProfesorController: <font size=8>cargarProfesor(profesorId) : Profesor

ProfesorController --> ProfesorRepository: <font size=8>obtener(profesorId) : Profesor

EditarProfesorView --> ProfesorController: <font size=8>validarDatosObligatorios(nombre, email) : boolean

EditarProfesorView --> ProfesorController: <font size=8>emailEnUsoPorOtro(email, profesorId) : boolean

ProfesorController --> ProfesorRepository: <font size=8>obtenerPorEmailDeOtro(email, profesorId) : Profesor

EditarProfesorView --> ProfesorController: <font size=8>guardarCambios(profesorId, nombre, email) : boolean

ProfesorController --> Profesor: <font size=8>actualizar(nombre, email)

ProfesorController --> ProfesorRepository: <font size=8>editar(profesor)

ProfesorRepository -- Profesor

EditarProfesorView --> ProfesorAbiertoSalida: <font size=8>datos actualizados

@enduml
